spring.application.name=skillbridge

spring.datasource.url=jdbc:mysql://${mysql.railway.internal}:${3306}/${railway}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=${root}
spring.datasource.password=${dpIrllHMjPuZPkEgcsFYVFLqIwcVBKHh}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true